# Generated by Django 4.1.3 on 2022-11-30 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['created_date']},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='content',
        ),
    ]
