# Generated by Django 4.1.3 on 2022-12-05 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='content',
            new_name='description',
        ),
    ]
