# Generated by Django 4.1.3 on 2022-12-05 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_content_course_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
